import { describe, expect, test } from 'bun:test'
import { COMMON_PART_PRESETS, KNOWN_PART_ROLES } from '../src/presets/common-parts'
import { MESSAGE_LAYOUT_AUDITS } from '../src/presets/message-anatomy'
import { STYLE_LIBRARY_PACKS, STYLE_LIBRARY_RECIPES, packCompatiblePresetIds, packDefaultPresetIds, packDefaultPresetIdsForLayout, packPresetIds, styleLibraryFamilies } from '../src/presets/style-library'

describe('style library registry', () => {
  test('indexes every quick style in searchable metadata', () => {
    expect(STYLE_LIBRARY_RECIPES).toHaveLength(COMMON_PART_PRESETS.length)
    expect(new Set(STYLE_LIBRARY_RECIPES.map((entry) => entry.preset.id))).toEqual(new Set(COMMON_PART_PRESETS.map((entry) => entry.id)))
    for (const entry of STYLE_LIBRARY_RECIPES) {
      expect(entry.area.length).toBeGreaterThan(0)
      expect(entry.family.length).toBeGreaterThan(0)
      expect(entry.scale.length).toBeGreaterThan(0)
      expect(entry.supports.length).toBeGreaterThan(0)
      expect(entry.keywords.length).toBeGreaterThan(0)
    }
    expect(styleLibraryFamilies()).toContain('Editorial')
    expect(styleLibraryFamilies()).toContain('Terminal')
    expect(styleLibraryFamilies()).toContain('Manga')
    expect(styleLibraryFamilies()).toContain('Journal')
    expect(styleLibraryFamilies()).toEqual([...new Set(STYLE_LIBRARY_RECIPES.map((entry) => entry.family))].sort((a, b) => a.localeCompare(b)))
  })

  test('keeps legacy Bubble recipes honest while packs introduce explicit Minimal adapters', () => {
    const packRecipeIds = new Set(STYLE_LIBRARY_PACKS.flatMap((pack) => packPresetIds(pack)))
    const oldMessageRecipes = STYLE_LIBRARY_RECIPES.filter((entry) => ['message', 'prose', 'avatar'].includes(entry.area) && !packRecipeIds.has(entry.preset.id))
    expect(oldMessageRecipes.length).toBeGreaterThan(0)
    for (const entry of oldMessageRecipes) {
      expect(entry.supports).toContain('bubble')
      expect(entry.supports).not.toContain('minimal')
    }
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'manga-panel-portrait')?.supports).toEqual(['bubble'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'manga-margin-speaker')?.supports).toEqual(['minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'manga-ink-frame')?.supports).toEqual(['bubble', 'minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'editorial-feature-lead')?.supports).toEqual(['bubble'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'editorial-column-rule')?.supports).toEqual(['minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'editorial-heading-set')?.supports).toEqual(['bubble', 'minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'minimal-actions-overlay')?.supports).toEqual(['minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'minimal-native-strip-off')?.supports).toEqual(['minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'message-greetings-editorial')?.supports).toEqual(['bubble', 'minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'message-swipes-compact')?.supports).toEqual(['bubble', 'minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'message-thinking-editorial')?.supports).toEqual(['bubble', 'minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'message-thinking-manga')?.supports).toEqual(['bubble', 'minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'manga-read-more')?.supports).toEqual(['bubble', 'minimal'])
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'editorial-read-more')?.supports).toEqual(['bubble', 'minimal'])
  })

  test('MinimalMessage anatomy is mapped independently from BubbleMessage', () => {
    const minimal = MESSAGE_LAYOUT_AUDITS.minimal
    expect(minimal.component).toBe('MinimalMessage')
    expect(minimal.catalogClasses).toContain('actionsWrap')
    expect(minimal.catalogClasses).not.toContain('actionsPill')
    expect(minimal.roles.frame?.[0].selector).toBe('[data-component="MinimalMessage"]')
    expect(minimal.roles['avatar-frame']?.[0].selector).toContain('_avatar_')
    expect(minimal.roles['meta-pill']?.[0].selector).toContain('_metaPill_')
    expect(minimal.roles.actions?.[0].selector).toContain('_actionsWrap_')
    expect(minimal.roles.thinking?.[0].selector).toContain('data-reasoning-toggle')
    expect(MESSAGE_LAYOUT_AUDITS.bubble.roles.thinking?.[0].selector).toContain('data-reasoning-toggle')
    expect(MESSAGE_LAYOUT_AUDITS.bubble.roles.greetings?.[0].selector).toContain('Browse alternate greetings')
    expect(MESSAGE_LAYOUT_AUDITS.bubble.roles['long-message-toggle']?.[0].selector).toContain('_longMessageTogglePill_')
    expect(minimal.roles['long-message-toggle']?.[0].selector).toContain('_longMessageTogglePill_')
    expect(KNOWN_PART_ROLES['message.thinking.toggle'].selectors[0].selector).toContain('_toggle_')
    expect(MESSAGE_LAYOUT_AUDITS.bubble.roles.actions?.[0].selector).toContain('BubbleActions')
    expect(minimal.roles['header-left']).toBeUndefined()
    expect(minimal.roles['meta-wrap']).toBeUndefined()
    expect(minimal.roles['avatar-backdrop']).toBeUndefined()
    expect(KNOWN_PART_ROLES['minimal.actions'].selectors[0].selector).toContain('_actionsWrap_')
  })

  test('Manga is a pack with a non-conflicting apply-all core and optional alternates', () => {
    const manga = STYLE_LIBRARY_PACKS.find((pack) => pack.id === 'manga')
    expect(manga).toBeDefined()
    expect(packPresetIds(manga!)).toContain('manga-sticker-portrait')
    expect(packPresetIds(manga!)).toContain('manga-ink-frame')
    expect(packDefaultPresetIds(manga!)).toContain('manga-panel-portrait')
    expect(packDefaultPresetIds(manga!)).toContain('manga-margin-speaker')
    expect(packDefaultPresetIds(manga!)).toContain('manga-body-copy')
    expect(packDefaultPresetIds(manga!)).toContain('manga-greetings-tag')
    expect(packDefaultPresetIds(manga!)).toContain('manga-swipe-strip')
    expect(packDefaultPresetIds(manga!)).toContain('manga-read-more')
    expect(packDefaultPresetIds(manga!)).toContain('manga-scroll-cue')
    expect(packDefaultPresetIds(manga!)).toContain('minimal-native-strip-off')
    expect(packDefaultPresetIds(manga!)).not.toContain('manga-sticker-portrait')
    expect(packDefaultPresetIds(manga!)).not.toContain('manga-ink-frame')
    expect(manga!.assetSlots.map((slot) => slot.id)).toEqual(['portrait', 'screen', 'corner-art', 'thinking-mark', 'temper-ornament'])
    expect(manga!.assetSlots.find((slot) => slot.id === 'temper-ornament')).toMatchObject({ placement: 'plane-stencil', builtInIds: ['manga-anger','impact-burst','four-spark','sweat-drop'] })
    expect(manga!.assetSlots.find((slot) => slot.id === 'corner-art')).toMatchObject({ defaultAnchor: 'message.frame', defaultSurface: 'before' })
    expect(manga!.assetSlots.find((slot) => slot.id === 'thinking-mark')).toMatchObject({ defaultAnchor: 'message.thinking.icon', placement: 'stencil', defaultSize: 14 })
    expect(manga!.defaultPalette).toEqual({ accent: '#ffffff', text: '#f4f1e9', intensity: 100 })
  })

  test('pack workbench compatibility can stage Bubble and Minimal independently', () => {
    const manga = STYLE_LIBRARY_PACKS.find((pack) => pack.id === 'manga')!
    expect(packCompatiblePresetIds(manga, 'bubble')).toContain('manga-panel-portrait')
    expect(packCompatiblePresetIds(manga, 'bubble')).not.toContain('manga-margin-speaker')
    expect(packCompatiblePresetIds(manga, 'minimal')).toContain('manga-margin-speaker')
    expect(packCompatiblePresetIds(manga, 'minimal')).not.toContain('manga-panel-portrait')
    expect(packDefaultPresetIdsForLayout(manga, 'bubble')).toContain('manga-panel-portrait')
    expect(packDefaultPresetIdsForLayout(manga, 'bubble')).not.toContain('manga-margin-speaker')
    expect(packDefaultPresetIdsForLayout(manga, 'minimal')).toContain('manga-margin-speaker')
    expect(packDefaultPresetIdsForLayout(manga, 'minimal')).not.toContain('manga-panel-portrait')
    expect(packDefaultPresetIdsForLayout(manga, 'all')).toEqual(packDefaultPresetIds(manga))
  })

  test('Editorial is a second full pack with layout-specific leads and restrained alternates', () => {
    const editorial = STYLE_LIBRARY_PACKS.find((pack) => pack.id === 'editorial')
    expect(editorial).toBeDefined()
    expect(editorial!.preview).toBe('editorial')
    expect(packPresetIds(editorial!)).toHaveLength(15)
    expect(packPresetIds(editorial!)).toContain('editorial-author-portrait')
    expect(packPresetIds(editorial!)).toContain('editorial-byline')
    expect(packDefaultPresetIds(editorial!)).toContain('editorial-feature-lead')
    expect(packDefaultPresetIds(editorial!)).toContain('editorial-actions-rail')
    expect(packDefaultPresetIds(editorial!)).toContain('editorial-column-rule')
    expect(packDefaultPresetIds(editorial!)).toContain('editorial-user-correspondent')
    expect(packDefaultPresetIds(editorial!)).toContain('editorial-heading-set')
    expect(packDefaultPresetIds(editorial!)).toContain('editorial-read-more')
    expect(packDefaultPresetIds(editorial!)).not.toContain('editorial-author-portrait')
    expect(packDefaultPresetIds(editorial!)).not.toContain('editorial-byline')
    expect(editorial!.assetSlots.map((slot) => slot.id)).toEqual(['portrait', 'masthead', 'thinking-mark'])
    expect(editorial!.assetSlots.find((slot) => slot.id === 'masthead')).toMatchObject({ defaultAnchor: 'header.root', defaultSurface: 'after' })
    expect(editorial!.assetSlots.find((slot) => slot.id === 'thinking-mark')).toMatchObject({ defaultAnchor: 'message.thinking.icon', placement: 'stencil', defaultSize: 12 })
    expect(editorial!.defaultPalette).toEqual({ accent: '#92a6b3', text: '#ece8df', intensity: 78 })
  })

  test('Editorial workbench defaults split cleanly between Bubble and Minimal', () => {
    const editorial = STYLE_LIBRARY_PACKS.find((pack) => pack.id === 'editorial')!
    expect(packCompatiblePresetIds(editorial, 'bubble')).toContain('editorial-feature-lead')
    expect(packCompatiblePresetIds(editorial, 'bubble')).toContain('editorial-actions-rail')
    expect(packCompatiblePresetIds(editorial, 'bubble')).not.toContain('editorial-column-rule')
    expect(packCompatiblePresetIds(editorial, 'minimal')).toContain('editorial-column-rule')
    expect(packCompatiblePresetIds(editorial, 'minimal')).toContain('editorial-user-correspondent')
    expect(packCompatiblePresetIds(editorial, 'minimal')).not.toContain('editorial-feature-lead')
    expect(packCompatiblePresetIds(editorial, 'minimal')).not.toContain('editorial-actions-rail')
    expect(packDefaultPresetIdsForLayout(editorial, 'bubble')).toContain('editorial-feature-lead')
    expect(packDefaultPresetIdsForLayout(editorial, 'bubble')).not.toContain('editorial-column-rule')
    expect(packDefaultPresetIdsForLayout(editorial, 'minimal')).toContain('editorial-column-rule')
    expect(packDefaultPresetIdsForLayout(editorial, 'minimal')).not.toContain('editorial-feature-lead')
    expect(packDefaultPresetIdsForLayout(editorial, 'minimal')).toContain('editorial-reading-column')
    expect(packDefaultPresetIdsForLayout(editorial, 'minimal')).toContain('minimal-actions-overlay')
    expect(packDefaultPresetIdsForLayout(editorial, 'minimal')).toContain('minimal-native-strip-off')
    expect(packDefaultPresetIdsForLayout(editorial, 'bubble')).not.toContain('minimal-actions-overlay')
    expect(packDefaultPresetIdsForLayout(editorial, 'bubble')).not.toContain('minimal-native-strip-off')
    expect(packPresetIds(editorial)).toContain('message-greetings-editorial')
    expect(packPresetIds(editorial)).toContain('message-swipes-compact')
    expect(packPresetIds(editorial)).toContain('message-thinking-editorial')
    expect(packPresetIds(editorial)).toContain('editorial-read-more')
    expect(packDefaultPresetIdsForLayout(editorial, 'minimal')).toContain('message-thinking-editorial')
    expect(packDefaultPresetIds(editorial)).toContain('message-greetings-editorial')
    expect(packDefaultPresetIds(editorial)).toContain('message-swipes-compact')
    expect(packDefaultPresetIds(editorial)).toContain('editorial-read-more')
  })

  test('Visual Novel includes its long-message route control in Apply All', () => {
    const vn = STYLE_LIBRARY_PACKS.find((pack) => pack.id === 'visual-novel')
    expect(vn).toBeDefined()
    expect(packDefaultPresetIds(vn!)).toContain('visual-novel-read-more')
    expect(packDefaultPresetIds(vn!)).toContain('visual-novel-attachments')
    expect(packDefaultPresetIds(vn!)).toContain('visual-novel-prose')
    expect(packDefaultPresetIds(vn!)).toContain('visual-novel-greetings')
    expect(packPresetIds(vn!)).toContain('visual-novel-read-more')
    expect(packPresetIds(vn!)).toContain('visual-novel-attachments')
    expect(packPresetIds(vn!)).toContain('visual-novel-prose')
    expect(packPresetIds(vn!)).toContain('visual-novel-greetings')
    expect(vn!.areas).toContain('prose')
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'visual-novel-read-more')?.family).toBe('Visual Novel')
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'visual-novel-attachments')?.family).toBe('Visual Novel')
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'visual-novel-prose')?.family).toBe('Visual Novel')
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'visual-novel-greetings')?.family).toBe('Visual Novel')
  })

  test('non-Manga packs ship their own modern raw/native media recipe', () => {
    const editorial = STYLE_LIBRARY_PACKS.find((pack) => pack.id === 'editorial')!
    const vn = STYLE_LIBRARY_PACKS.find((pack) => pack.id === 'visual-novel')!
    const journal = STYLE_LIBRARY_PACKS.find((pack) => pack.id === 'journal')!
    expect(packDefaultPresetIds(editorial)).toContain('editorial-media-plate')
    expect(packDefaultPresetIds(vn)).toContain('visual-novel-attachments')
    expect(packDefaultPresetIds(journal)).toContain('journal-photo-insert')
  })

  test('Journal is a full assemblage pack with bundled ornament slots', () => {
    const journal = STYLE_LIBRARY_PACKS.find((pack) => pack.id === 'journal')
    expect(journal).toBeDefined()
    expect(journal!.preview).toBe('journal')
    expect(journal!.defaultPalette).toEqual({ accent: '#8db5b0', text: '#4b5553', intensity: 72 })
    expect(packDefaultPresetIds(journal!)).toContain('journal-polaroid-note')
    expect(packDefaultPresetIds(journal!)).toContain('journal-entry-ledger')
    expect(packDefaultPresetIds(journal!)).toContain('journal-minimal-card')
    expect(packDefaultPresetIds(journal!)).not.toContain('journal-washi-photo')
    expect(packPresetIds(journal!)).not.toContain('journal-washi-photo')
    expect(STYLE_LIBRARY_RECIPES.find((entry) => entry.preset.id === 'journal-washi-photo')).toBeUndefined()
    expect(packDefaultPresetIds(journal!)).toContain('journal-corner-sticker')
    expect(packDefaultPresetIds(journal!)).toContain('journal-thinking-note')
    expect(packDefaultPresetIds(journal!)).toContain('journal-page-pager')
    expect(packDefaultPresetIds(journal!)).toContain('journal-paper-actions')
    expect(packDefaultPresetIds(journal!)).toContain('journal-scroll-stamp')
    expect(packDefaultPresetIds(journal!)).toContain('journal-pasted-ephemera')
    expect(packDefaultPresetIds(journal!)).toContain('journal-composer')
    expect(packCompatiblePresetIds(journal!, 'bubble')).toContain('journal-polaroid-note')
    expect(packCompatiblePresetIds(journal!, 'bubble')).toContain('journal-entry-ledger')
    expect(packCompatiblePresetIds(journal!, 'bubble')).not.toContain('journal-minimal-card')
    expect(packCompatiblePresetIds(journal!, 'minimal')).toContain('journal-minimal-card')
    expect(packCompatiblePresetIds(journal!, 'minimal')).not.toContain('journal-polaroid-note')
    expect(packCompatiblePresetIds(journal!, 'minimal')).not.toContain('journal-entry-ledger')
    expect(journal!.assetSlots.map((slot) => slot.id)).toEqual(['photo-pin','page-sticker','divider-ornament','ephemera-tape','thinking-mark'])
    expect(journal!.assetSlots.find((slot) => slot.id === 'photo-pin')).toMatchObject({ placement: 'plane-stencil', builtInIds: ['washi-tape','paperclip','four-spark','tiny-flower'] })
    expect(journal!.assetSlots.find((slot) => slot.id === 'ephemera-tape')).toMatchObject({ placement: 'plane-stencil', defaultAnchor: 'message.html-island' })
    expect(journal!.assetSlots.find((slot) => slot.id === 'thinking-mark')).toMatchObject({ placement: 'stencil', defaultSize: 13 })

    const polaroid = COMMON_PART_PRESETS.find((preset) => preset.id === 'journal-polaroid-note')!
    const content = polaroid.steps.find((step) => step.role === 'message.content')!
    const basePackets = content.createPackets()
    expect(basePackets.find((packet) => packet.type === 'position')).toMatchObject({ type: 'position', mode: 'flow', flowAlign: 'center' })
    expect(basePackets.find((packet) => packet.type === 'size')).toMatchObject({ type: 'size', width: { mode: 'parent' }, maxWidth: { mode: 'fixed', value: 760, unit: 'px' } })
    expect(content.createMobilePackets?.().find((packet) => packet.type === 'position')).toBeUndefined()

    const ephemera = COMMON_PART_PRESETS.find((preset) => preset.id === 'journal-pasted-ephemera')!
    expect(ephemera.steps.find((step) => step.role === 'message.html-island')?.createPackets().find((packet) => packet.type === 'shadow')).toBeDefined()
    expect(ephemera.steps.find((step) => step.role === 'message.html-island.back')?.createPackets().find((packet) => packet.type === 'shadow')).toMatchObject({ type: 'shadow', y: 12, alpha: .56 })
  })

})
